steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "terraform" ]; then
        cd terraform
        terraform init
      else
        echo "***************************** SKIPPING INITING *******************************"
        echo "terraform directory is not found"
        echo "*******************************************************************************"
      fi 

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform" ]; then
        cd terraform
        export TF_VAR_project_id=${PROJECT_ID}
        terraform plan -var-file="dev.tfvars" 
      else
        echo "***************************** SKIPPING PLANING *******************************"
        echo "terraform directory is not found"
        echo "*******************************************************************************"
      fi 
  secretEnv: ['TF_VAR_dbpassword','TF_VAR_alert_email_address','TF_VAR_backend_domain','TF_VAR_domain','TF_VAR_iap_brand_name']
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
      if [ -d "terraform" ]; then
        cd terraform
        export TF_VAR_project_id=${PROJECT_ID}
        terraform apply -auto-approve -var-file="dev.tfvars" 
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "terraform directory is not found"
        echo "*******************************************************************************"
      fi
  secretEnv: ['TF_VAR_dbpassword','TF_VAR_alert_email_address','TF_VAR_backend_domain','TF_VAR_domain','TF_VAR_iap_brand_name']
# [END tf-apply]
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/dbpassword/versions/latest
    env: 'TF_VAR_dbpassword'
  - versionName: projects/${PROJECT_ID}/secrets/alert_email_address/versions/latest
    env: 'TF_VAR_alert_email_address'
  - versionName: projects/${PROJECT_ID}/secrets/backend_domain/versions/latest
    env: 'TF_VAR_backend_domain'
  - versionName: projects/${PROJECT_ID}/secrets/domain/versions/latest
    env: 'TF_VAR_domain'
  - versionName: projects/${PROJECT_ID}/secrets/iap_brand_name/versions/latest
    env: 'TF_VAR_iap_brand_name'
timeout: 3600s